In [79]:
import pandas as pd
import os
import csv

from sqlalchemy import create_engine

In [80]:
df = pd.read_csv('./attacks.csv', encoding="windows-1252")

In [81]:
df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [82]:
# Drop the desired columns
columns_to_drop = ['Location', 'Investigator or Source', 'pdf', 'href formula', 'href', 'Case Number.1', 'Case Number.2', 'original order']
df = df.drop(columns_to_drop, axis=1)

# Save the modified DataFrame back to a CSV file
df.to_csv('cleaned-attacks.csv', index=False)

In [83]:
df.head()

,Case Number,Date,Year,Type,Country,Area,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",NaN,NaN

In [84]:
columns_to_drop = ['Species ','Unnamed: 22', 'Unnamed: 23' ]
df = df.drop(columns_to_drop, axis=1)

In [85]:
df.head(50)

,Case Number,Date,Year,Type,Country,Area,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Kite surfing,Chris …,M,NaN,"No injury, board bitten",N,NaN
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon
7,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,Walking,Cody High,M,15,Lower left leg bitten,N,17h00
9,2018.05.26.a,26-May-2018,2018.0,Unprovoked,USA,Florida,Standing,male,M,12,Minor injury to foot,N,14h00
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Feeding sharks,male,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning
11,2018.05.21,21-May-2018,2018.0,Unprovoked,USA,South Carolina,Boogie boarding,Trey de Boer,M,10,Injuries to lower right leg and foot,N,NaN
12,2018.05.13.b,13-May-2018,2018.0,Unprovoked,USA,South Carolina,Swimming,Jei Turrell,M,10,Severe bite to right forearm,N,15h00
13,2018.05.13.a,13-May-2018,2018.0,Invalid,ENGLAND,Cornwall,Fishing,Max Berryman,M,21,Injured by teeth of a dead porbeagle shark he ...,N,08h15
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Feeding sharks,Melisa Brunning,F,34,Shallow lacerations to finger PROVOKED INCIDENT,N,NaN
15,2018.05.12,12-May-2018,2018.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,Surfing,male,M,NaN,"Minor injury, marks on board",N,11h00
16,2018.05.09,09-May-2018,2018.0,Questionable,AUSTRALIA,New South Wales,Surfing,male,M,NaN,"No injury, surfboard damaged",N,10h30
17,2018.04.30.R,Reported 30-Apr-2018,2018.0,Unprovoked,THAILAND,Hua Hin,Swimming,female,M,NaN,Minor injury to ankle,N,NaN
18,2018.04.28.b,28-Apr-2018,2018.0,Unprovoked,COSTA RICA,Cocos Island,Scuba diving,male,M,30,"No injury, shark bit scuba gear",N,10h40
19,2018.04.28.a,28-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Surfing,Adam Murray,M,NaN,"No injury, knocked off board by shark",N,16h50
20,2018.04.25.b,25-Apr-2018,2018.0,Questionable,AUSTRALIA,New South Wales,Surfing,Matthew Lee,M,NaN,No injury,N,07h00
21,2018.04.25.a,25-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Surfing,Rob Bruce,M,60,"No injury, knocked off board by shark",N,09h30
22,2018.04.24,24-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Surfing,Nathan Burch,M,NaN,"No injury, shark struck his leg",N,Afternoon
23,2018.04.23,23-Apr-2018,2018.0,Unprovoked,MALDIVES,Alifu Alifu Atoll,Fishing,Ahmed Rasheed,M,32,5-inch cut to hand,N,21h50
24,2018.04.22,22-Apr-2018,2018.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Paddle-skiing,male,M,33,"No injury, shark bit hole in ski",N,09h40
25,2018.04.19,19-Apr-2018,2018.0,Unprovoked,USA,Hawaii,Body boarding,Dylan McWilliams,M,29,Lacerations to right lower leg,N,NaN
26,2018.04.15.d,15-Apr-2018,2018.0,Unprovoked,THAILAND,Hua Hin,Swimming,Werner Danielsen,M,54,Lacerations to foot and ankle,N,NaN
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN
28,2018.04.15.b,15-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Surfing,Jason Longrass,M,41,Laceration to right thigh,N,NaN
29,2018.04.15.a,15-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Surfing,Alejandro Travaglini,M,37,Lacerations to legs,N,08h00
30,2018.04.14,14-Apr-2018,2018.0,Unprovoked,BAHAMAS,New Providence,Surfing,Bruce Rowan,M,NaN,No Injury. Shark swam away with the surf board,N,09h30
31,2018.04.10.R,Reported 10-Apr-2018,2018.0,Invalid,BRAZIL,Alagoas,Fishing,Josias Paz,M,56,Injury to ankle from marine animal trapped in ...,N,NaN
32,2018.04.09,09-Apr-2018,2018.0,Unprovoked,NEW CALEDONIA,NaN,Windsurfing,NaN,NaN,NaN,"No injury, shark bit board",N,17h00
33,2018.04.05,05-Apr-2018,2018.0,Unprovoked,BAHAMAS,NaN,Swimming,Shane McConnell,M,12,"2 puncture wounds to left foot, abrasion to ri...",N,18h00
34,2018.04.03,03-Apr-2018,2018.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,Surfing,Ross Spowart,M,19,Lacerations to left knee & lower leg,N,15h00
35,2018.03.31,31-Mar-2018,2018.0,Unprovoked,USA,Hawaii,Stand-Up Paddleboarding,male,M,25,Injuries to right leg & hand,N,09h30
36,2018.03.14,14-Mar-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Wading,Luke Guy & Finn Bald,M,10,Minor injuries to legs,N,17h35
37,2018.03.09.b,9-Mar-2018,2018.0,Unprovoked,AUSTRALIA,Victoria,Swimming,Rob Crossland,M,69,"No injury, said to have been charged by sharks...",N,15h30
38,2018.03.09.a,9-Mar-2018,2018.0,Unprovoked,AUSTRALIA,Victoria,Surfing,Lachie Brown,M,18,"Minor injury, ankle grazed",N,07h30
39,2018.02.24,24-Feb-2018,2018.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Scuba Diving,Elton Polly,M,38,The shark & man simply collided; neither were...,N,NaN
40,2018.02.23,23-Feb-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Swimming,Anna Shurapey,F,55,Laceratons to right leg & foot,N,"19h00, Dusk"
41,2018.02.17,18-Feb-2018,2018.0,Provoked,AUSTRALIA,Victoria,Kayak fishing for sharks,Brett Palmer,M,34,"Shark rammed kayak, no injury to occupant PRO...",N,Night
42,2018.02.15,15-Feb-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Walking,Adam Hoare,M,35,Puncture wounds to leff foot & lower leg,N,16h00
43,2018.02.14,14-Feb-2018,2018.0,Invalid,AUSTRALIA,Queensland,Swimming,Sharna Babd,F,NaN,"Collision / No injury, no attack",N,18h00
44,2018.02.11,11-Feb-2018,2018.0,Invalid,BRAZIL,"Boi Island, Victoria",Cleaning fish,Rosalida Souza,F,46,Lacerations to 4 toes of right foot,N,NaN
45,2018.02.03,03-Feb-2018,2018.0,Unprovoked,ECUADOR,Galapagos Islands,Snorkeling,Andrew Phipps Newman,M,45,Injuries to right foot,N,NaN
46,2018.02.01,01-Feb-2018,2018.0,Invalid,AUSTRALIA,Western Australia,Spearfishing,Lucas Martin,M,14,"No injury no attack. This is considerd an ""enc...",N,NaN
47,2018.01.28,28-Jan-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,NaN,male,M,18,Injuries to right leg,N,08h00
48,2018.01.21,21-Jan-2018,2018.0,Unprovoked,NEW CALEDONIA,NaN,Spearfishing,male,M,40s,Injuries to abdomen and arm,N,15h30
49,2018.01.14,14-Jan-2018,2018.0,Unprovoked,AUSTRALIA,Queensland,Diving,Mathew Vickers,M,NaN,Severe laceration to left forearm,N,15h01

In [86]:
df['Case Number'].count()

8702

In [87]:
#drop rows that dont have data
dropped_missing_data = df.dropna(subset=['Case Number','Date', 'Year', 'Type', 'Country', 'Area' , 'Activity', 'Name', 'Age', 'Injury','Time'])

In [88]:
# Delete rows with NaN values in any column
df = df.dropna(how='any')

In [89]:
df['Case Number'].count()

2169

In [90]:
df.head(50)

,Case Number,Date,Year,Type,Country,Area,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,Walking,Cody High,M,15,Lower left leg bitten,N,17h00
9,2018.05.26.a,26-May-2018,2018.0,Unprovoked,USA,Florida,Standing,male,M,12,Minor injury to foot,N,14h00
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Feeding sharks,male,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning
12,2018.05.13.b,13-May-2018,2018.0,Unprovoked,USA,South Carolina,Swimming,Jei Turrell,M,10,Severe bite to right forearm,N,15h00
13,2018.05.13.a,13-May-2018,2018.0,Invalid,ENGLAND,Cornwall,Fishing,Max Berryman,M,21,Injured by teeth of a dead porbeagle shark he ...,N,08h15
18,2018.04.28.b,28-Apr-2018,2018.0,Unprovoked,COSTA RICA,Cocos Island,Scuba diving,male,M,30,"No injury, shark bit scuba gear",N,10h40
21,2018.04.25.a,25-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Surfing,Rob Bruce,M,60,"No injury, knocked off board by shark",N,09h30
23,2018.04.23,23-Apr-2018,2018.0,Unprovoked,MALDIVES,Alifu Alifu Atoll,Fishing,Ahmed Rasheed,M,32,5-inch cut to hand,N,21h50
24,2018.04.22,22-Apr-2018,2018.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Paddle-skiing,male,M,33,"No injury, shark bit hole in ski",N,09h40
29,2018.04.15.a,15-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Surfing,Alejandro Travaglini,M,37,Lacerations to legs,N,08h00
34,2018.04.03,03-Apr-2018,2018.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,Surfing,Ross Spowart,M,19,Lacerations to left knee & lower leg,N,15h00
35,2018.03.31,31-Mar-2018,2018.0,Unprovoked,USA,Hawaii,Stand-Up Paddleboarding,male,M,25,Injuries to right leg & hand,N,09h30
36,2018.03.14,14-Mar-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Wading,Luke Guy & Finn Bald,M,10,Minor injuries to legs,N,17h35
37,2018.03.09.b,9-Mar-2018,2018.0,Unprovoked,AUSTRALIA,Victoria,Swimming,Rob Crossland,M,69,"No injury, said to have been charged by sharks...",N,15h30
38,2018.03.09.a,9-Mar-2018,2018.0,Unprovoked,AUSTRALIA,Victoria,Surfing,Lachie Brown,M,18,"Minor injury, ankle grazed",N,07h30
40,2018.02.23,23-Feb-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Swimming,Anna Shurapey,F,55,Laceratons to right leg & foot,N,"19h00, Dusk"
41,2018.02.17,18-Feb-2018,2018.0,Provoked,AUSTRALIA,Victoria,Kayak fishing for sharks,Brett Palmer,M,34,"Shark rammed kayak, no injury to occupant PRO...",N,Night
42,2018.02.15,15-Feb-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Walking,Adam Hoare,M,35,Puncture wounds to leff foot & lower leg,N,16h00
51,2018.01.12,12-Jan-2018,2018.0,Unprovoked,BRAZIL,Fernando de Noronha,Surfing,Ricardo Ferrari Bulhoes,M,20,Minor injury to left forearm,N,Late afternoon
53,2017.12.31,31-Dec-2017,2017.0,Unprovoked,USA,Hawaii,Surfing,Marjorie Mariano,F,54,Severe lacerations to left thigh & knee,N,18h00
54,2017.12.30,30-Dec-2017,2017.0,Unprovoked,USA,California,Surfing,Natalie Jones,F,35,Foot bitten,N,12h00
60,2017.11.24,24-Nov-2017,2017.0,Unprovoked,USA,California,Spearfishing,Grigor Azatian,M,25,Right leg bitten,N,13h45
61,2017.11.18,18-Nov-2017,2017.0,Unprovoked,USA,Florida,Surfing,Kaia Anderson,F,14,Heel bitten,N,Late afternoon
63,2017.11.13,13-Nov-2017,2017.0,Unprovoked,AUSTRALIA,New South Wales,Surfing,Charlie Fry,M,25,Puncture wounds to left shoulder,N,16h00
64,2017.11.04,04-Nov-2017,2017.0,Unprovoked,CUBA,Holquin Province,Night bathing,Jesús Cabrera González,M,22,FATAL,Y,23h30
66,2017.10.28,28-Oct-2017,2017.0,Unprovoked,AUSTRALIA,New South Wales,Surfing,male,M,31,Minor injury to foot,N,09h00
69,2017.10.23.b,23-Oct-2017,2017.0,Unprovoked,USA,Florida,Surfing,Jason Hartl,M,17,Lacerations to left foot,N,17h00
70,2017.10.23.a,23-Oct-2017,2017.0,Unprovoked,USA,Florida,Swimming,Susan Peteka,F,60,Severe lacerations to left hand & wrist,N,08h00
71,2017.10.22,22-Oct-2017,2017.0,Unprovoked,AUSTRALIA,South Australia,Kayaking / Fishing,Sarah Williams,F,15,Minor injuries,N,Afternoon
74,2017.10.09,09-Oct-2017,2017.0,Unprovoked,USA,Hawaii,Surfing,Mitch Milan,M,54,Lacerations to left hand,N,18h30
75,2017.10.05,05-Oct-2017,2017.0,Unprovoked,USA,Hawaii,Snorkeling,female,F,40,Abrasions,N,12h30
83,2017.09.16.a,16-Sep-2017,2017.0,Unprovoked,USA,Florida,Surfing,male,M,28,Lacerations to left foot,N,16h30
87,2017.09.13,13-Sep-2017,2017.0,Unprovoked,USA,Florida,Surfing,Benjamin Loyd,M,18,Lacerations to left foot,N,18h45
89,2017.09.10.a,10-Sep-2017,2017.0,Unprovoked,AUSTRALIA,New South Wales,Surfing,Abe McGrath,M,35,Minor lacerations to right hip,N,06h00
92,2017.09.03.a,03-Sep-2017,2017.0,Unprovoked,JAPAN,Shizuoka Prefecture,Surfing,male,M,42,Injury to ankle & feet,N,10h00
95,2017.09.02.a,02-Sep-2017,2017.0,Unprovoked,USA,Florida,Surfing,Chase Elmore,M,17,Minor injury to right hand,N,10h44
96,2017.08.29,29-Aug-2017,2017.0,Unprovoked,AUSTRALIA,Victoria,Surfing,Marcel Brundler,M,37,"No injury, board bitten",N,10h30
97,2017.08.27,27-Aug-2017,2017.0,Unprovoked,USA,Florida,Wading,Violet Veatch,F,3,Leg injured,N,13h19
100,2017.08.23,23-Aug-2017,2017.0,Unprovoked,USA,Massachusetts,SUP,Cleveland Bigelow,M,69,Not injured by shark but board bitten,N,10h00
102,2017.08.10,10-Aug-2017,2017.0,Unprovoked,USA,South Carolina,Swimming,Linton Suttle,M,13,Minor cuts to sole & toes of left foot,N,13h30
104,2017.08.03,03-Aug-2017,2017.0,Provoked,USA,Massachusetts,Fishing,male,M,34,Foot bitten by landed shark PROVOKED INCIDENT,N,23h30
106,2017.07.31,31-Jul-2017,2017.0,Unprovoked,USA,Florida,Skimboarding,Colton McCarty,M,15,Lacerations to lower leg,N,18h30
111,2017.07.24,24-Jul-2017,2017.0,Unprovoked,"ST HELENA, British overseas territory",Ascension Island,Surfing,Kawika Matsu,M,37,Torso bitten,N,17h00
116,2017.07.20.b,20-Jul-2017,2017.0,Boating,USA,California,Kayaking,Bret Jackson,M,40,"No injury, kayak bitten",N,11h20
117,2017.07.20.a,20-Jul-2017,2017.0,Unprovoked,USA,California,SUP,Rolf Geyling,M,50,"No injury, shark bit paddleboard",N,07h45
121,2017.07.09,09-Jul-2017,2017.0,Unprovoked,USA,Florida,Swimming,Elvin Lanza,M,46,Lower legs bitten,N,15h30

In [91]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')
df = df.dropna(subset=['Date'])

In [92]:
df.head(10)

,Case Number,Date,Year,Type,Country,Area,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time
0,2018.06.25,2018-06-25,2018.0,Boating,USA,California,Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00
1,2018.06.18,2018-06-18,2018.0,Unprovoked,USA,Georgia,Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00
2,2018.06.09,2018-06-09,2018.0,Invalid,USA,Hawaii,Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45
6,2018.06.03.a,2018-06-03,2018.0,Unprovoked,BRAZIL,Pernambuco,Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon
8,2018.05.26.b,2018-05-26,2018.0,Unprovoked,USA,Florida,Walking,Cody High,M,15,Lower left leg bitten,N,17h00
9,2018.05.26.a,2018-05-26,2018.0,Unprovoked,USA,Florida,Standing,male,M,12,Minor injury to foot,N,14h00
10,2018.05.24,2018-05-24,2018.0,Provoked,AUSTRALIA,Queensland,Feeding sharks,male,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning
12,2018.05.13.b,2018-05-13,2018.0,Unprovoked,USA,South Carolina,Swimming,Jei Turrell,M,10,Severe bite to right forearm,N,15h00
13,2018.05.13.a,2018-05-13,2018.0,Invalid,ENGLAND,Cornwall,Fishing,Max Berryman,M,21,Injured by teeth of a dead porbeagle shark he ...,N,08h15
18,2018.04.28.b,2018-04-28,2018.0,Unprovoked,COSTA RICA,Cocos Island,Scuba diving,male,M,30,"No injury, shark bit scuba gear",N,10h40

In [93]:
df = df.drop('Time', axis=1)

In [94]:
df.head()

,Case Number,Date,Year,Type,Country,Area,Activity,Name,Sex,Age,Injury,Fatal (Y/N)
0,2018.06.25,2018-06-25,2018.0,Boating,USA,California,Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N
1,2018.06.18,2018-06-18,2018.0,Unprovoked,USA,Georgia,Standing,Adyson McNeely,F,11,Minor injury to left thigh,N
2,2018.06.09,2018-06-09,2018.0,Invalid,USA,Hawaii,Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N
6,2018.06.03.a,2018-06-03,2018.0,Unprovoked,BRAZIL,Pernambuco,Swimming,Jose Ernesto da Silva,M,18,FATAL,Y
8,2018.05.26.b,2018-05-26,2018.0,Unprovoked,USA,Florida,Walking,Cody High,M,15,Lower left leg bitten,N

In [95]:
df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Activity',
       'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)'],
      dtype='object')

In [96]:
df['Year'] = df['Year'].astype(int)

In [97]:
df.head()

,Case Number,Date,Year,Type,Country,Area,Activity,Name,Sex,Age,Injury,Fatal (Y/N)
0,2018.06.25,2018-06-25,2018,Boating,USA,California,Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N
1,2018.06.18,2018-06-18,2018,Unprovoked,USA,Georgia,Standing,Adyson McNeely,F,11,Minor injury to left thigh,N
2,2018.06.09,2018-06-09,2018,Invalid,USA,Hawaii,Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N
6,2018.06.03.a,2018-06-03,2018,Unprovoked,BRAZIL,Pernambuco,Swimming,Jose Ernesto da Silva,M,18,FATAL,Y
8,2018.05.26.b,2018-05-26,2018,Unprovoked,USA,Florida,Walking,Cody High,M,15,Lower left leg bitten,N

In [98]:
# Convert the 'Age' column to numeric, coerce non-numeric values to NaN
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

# Remove rows with non-numeric values in 'Age' column
df = df.dropna(subset=['Age'])

In [99]:
df.head(80)

,Case Number,Date,Year,Type,Country,Area,Activity,Name,Sex,Age,Injury,Fatal (Y/N)
0,2018.06.25,2018-06-25,2018,Boating,USA,California,Paddling,Julie Wolfe,F,57.0,"No injury to occupant, outrigger canoe and pad...",N
1,2018.06.18,2018-06-18,2018,Unprovoked,USA,Georgia,Standing,Adyson McNeely,F,11.0,Minor injury to left thigh,N
2,2018.06.09,2018-06-09,2018,Invalid,USA,Hawaii,Surfing,John Denges,M,48.0,Injury to left lower leg from surfboard skeg,N
6,2018.06.03.a,2018-06-03,2018,Unprovoked,BRAZIL,Pernambuco,Swimming,Jose Ernesto da Silva,M,18.0,FATAL,Y
8,2018.05.26.b,2018-05-26,2018,Unprovoked,USA,Florida,Walking,Cody High,M,15.0,Lower left leg bitten,N
...,...,...,...,...,...,...,...,...,...,...,...,...
181,2017.01.24,2017-01-24,2017,Unprovoked,BRAZIL,Pernambuco,Swimming,Arthur Andrade,M,21.0,Minor laceration to ring finger,N
183,2017.01.21,2017-01-21,2017,Unprovoked,AUSTRALIA,Queensland,Scuba Diving,Craig de Wit,M,55.0,"Multiple injuries to arm, wrist and torso",N
186,2017.01.09,2017-01-09,2017,Unprovoked,INDONESIA,Bali,Surfing,Daniel Moore,M,48.0,Injury to right wrist & forearm,N
188,2017.01.05,2017-01-05,2017,Unprovoked,USA,Florida,Wading,male,M,47.0,Minor injuries to foot,N
190,2016.12.27,2016-12-27,2016,Unprovoked,USA,Florida,Surfing,Zack Davis,M,16.0,Lacerations to right forearm,N

In [100]:
df['Age'] = df['Age'].astype(int)

In [101]:
df.head()

,Case Number,Date,Year,Type,Country,Area,Activity,Name,Sex,Age,Injury,Fatal (Y/N)
0,2018.06.25,2018-06-25,2018,Boating,USA,California,Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N
1,2018.06.18,2018-06-18,2018,Unprovoked,USA,Georgia,Standing,Adyson McNeely,F,11,Minor injury to left thigh,N
2,2018.06.09,2018-06-09,2018,Invalid,USA,Hawaii,Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N
6,2018.06.03.a,2018-06-03,2018,Unprovoked,BRAZIL,Pernambuco,Swimming,Jose Ernesto da Silva,M,18,FATAL,Y
8,2018.05.26.b,2018-05-26,2018,Unprovoked,USA,Florida,Walking,Cody High,M,15,Lower left leg bitten,N

In [102]:
columns = {'Case Number':str, 'Date':str, 'Year':int, 'Type':str, 'Country':str, 'Area':str, 'Activity':str,
       'Name':str, 'Sex ':str, 'Age':int, 'Injury':str, 'Fatal (Y/N)':str}

df = df.astype(columns)

In [103]:
df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Activity',
       'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)'],
      dtype='object')

In [104]:
df.columns = ['Case_Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal']

In [105]:
df.columns

Index(['Case_Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal'],
      dtype='object')

In [106]:
df['Sex'] = df['Sex'].str.strip()

In [107]:
df = df[df['Sex'] != 'lli']

In [108]:
value_counts = df['Sex'].value_counts()
value_counts

M    1806
F     300
Name: Sex, dtype: int64

In [109]:
# Save the modified DataFrame back to a CSV file
df.to_csv('cleaned-attacks.csv', index=False)

In [110]:
# Create database connection
connection_string= 'postgresql+psycopg2://postgres:1357@localhost:5432/Attacks_db'
engine = create_engine(connection_string)

In [111]:
df.to_sql('attacks', engine, index=False)

106

In [112]:
pd.read_sql('select * from attacks', engine)

,Case_Number,Date,Year,Type,Country,Area,Activity,Name,Sex,Age,Injury,Fatal
0,2018.06.25,2018-06-25,2018,Boating,USA,California,Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N
1,2018.06.18,2018-06-18,2018,Unprovoked,USA,Georgia,Standing,Adyson McNeely,F,11,Minor injury to left thigh,N
2,2018.06.09,2018-06-09,2018,Invalid,USA,Hawaii,Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N
3,2018.06.03.a,2018-06-03,2018,Unprovoked,BRAZIL,Pernambuco,Swimming,Jose Ernesto da Silva,M,18,FATAL,Y
4,2018.05.26.b,2018-05-26,2018,Unprovoked,USA,Florida,Walking,Cody High,M,15,Lower left leg bitten,N
...,...,...,...,...,...,...,...,...,...,...,...,...
2101,1862.12.22,1862-12-22,1862,Unprovoked,NEW ZEALAND,North Island,Swimming,Thomas Cooke,M,28,Right thigh and left foot severely bitten,N
2102,1858.03.14,1858-03-14,1858,Unprovoked,AUSTRALIA,Victoria,Bathing,Adolphe Bollander,M,22,FATAL,Y
2103,1837.01.17,1837-01-17,1837,Unprovoked,AUSTRALIA,New South Wales,Washing his feet,Alfred Australia Howe,M,12,"FATAL Injured by shark, died of tetanus",Y
2104,1817.05.11,1817-05-11,1817,Unprovoked,SRI LANKA,Western Province,Swimming,William May,M,22,FATAL,Y
2105,1703.03.26,1703-03-26,1703,Unprovoked,BARBADOS,Southwest coast,Swimming,"Samuel Jennings, a deserter from the British f...",M,19,"Hand and foot severely bitten, surgically ampu...",N

In [113]:
unique_values = df['Sex'].unique()

In [114]:
unique_values

array(['F', 'M'], dtype=object)

In [115]:
value_counts = df['Sex'].value_counts()

In [116]:
value_counts

M    1806
F     300
Name: Sex, dtype: int64